config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'

  resources :orders
  resources :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order

  def full_price
    unit_price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
    	format.html
    	format.pdf do
    		pdf = OrderPdf.new(@order)
    		send_data pdf.render,
    				  filename: "order_#{ @order.order_number }",
    				  type: 'application/pdf',
    				  disposition: 'inline'
    	end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])

    respond_to do |format|
    	format.html
    	format.pdf do
    		pdf = ReportPdf.new(@report)
    		send_data pdf.render,
    				  filename: "#{ @report.partner }_report_#{ @report.id }",
    				  type: 'application/pdf',
    				  disposition: 'inline'
    	end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrawnTrial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>
<ul>
<% @orders.each do |order| %>
  <li><%= link_to "Order \##{order.order_number}", order %></li>
<% end %>
</ul>

app/views/orders/show.html.erb
<h1>Order</h1>
<li><%= "Order \##{@order.order_number}" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Printable Receipt (PDF)", order_path(@order, format: 'pdf') %>
</li>

app/views/reports/index.html.erb
<h1>Reports</h1>
<ul>
<% @reports.each do |report| %>
  <li><%= link_to "Order \##{report.report_number}", report %></li>
<% end %>
</ul>

app/views/reports/show.html.erb
<h1>Report</h1>
<li><%= "Report \##{@report.partner}" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Printable Report (PDF)", report_path(@report, format: 'pdf') %>
</li>